### ISSUE TITLE
Bug in StringTrie<T>.find(String, int, int)

### ISSUE THREAD

**Issue by yhaskell** [OnPositive/wordnet#18]
ArrayIndexOutOfBounds exception on word "сурьезнейшая".

`java.lang.ArrayIndexOutOfBoundsException: -128`
`at com.onpositive.semantic.words3.hds.StringTrie.find (StringTrie.java:223)`
`at com.onpositive.semantic.words3.hds.StringTrie.get (StringTrie.java:41)`
`at com.onpositive.semantic.words3.ReadOnlyWordNet.getPossibleGrammarForms (ReadOnlyWordNet.java:559)`
`at com.onpositive.semantic.wordnet.composite.CompositeWordnet.getPossibleGrammarForms (CompositeWordnet.java:79)`

To test: `GrammarRelation[] possibleGrammarForms = wordNet.getPossibleGrammarForms("сурьезнейшая");`

**Comment by 32kda** [comment]
Fixed
